#
# (C) Copyright 2000-2007
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_VIDEO_SUNXI) += sunxi_display.o simplefb_common.o lcdc.o tve_common.o ../videomodes.o
obj-$(CONFIG_VIDEO_DE2) += sunxi_de2.o simplefb_common.o lcdc.o ../dw_hdmi.o sunxi_lcd.o sunxi_dw_hdmi.o
obj-$(CONFIG_VIDEO_DE3) += sunxi_de3.o lcdc.o ../dw_hdmi.o sun50i_dw_hdmi.o
